/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import PLProject.Admin;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Adminf extends javax.swing.JFrame {
      private Admin admin;
    public Adminf() {
        initComponents();
         addActions();
    } 
    public Adminf(Admin admin) {
        this.admin = admin;
        initComponents();
        welcomeAdmin();
        addActions(); 
    }
     private void welcomeAdmin() {
        if (admin != null) {
            jLabel2.setText("HELLO " + admin.getEmail() +
                    " - Today is a new chance to do better");
        }
    }
     @SuppressWarnings("unchecked")
    
    private void addActions() {
       usersbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Users page"));

       tasksbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Tasks page"));
        projectsbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Projects page"));
        employeebut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Employees page"));

       timecardsbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Time Cards page"));

        missionbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Missions page"));
        permissionbut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Permissions page"));

        leavebut.addActionListener(e ->
                JOptionPane.showMessageDialog(this, "Leave page"));

        
}
     private void logoutbutActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new Loginf().setVisible(true);
    }
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usersbut = new javax.swing.JButton();
        tasksbut = new javax.swing.JButton();
        projectsbut = new javax.swing.JButton();
        employeebut = new javax.swing.JButton();
        timecardsbut = new javax.swing.JButton();
        missionbut = new javax.swing.JButton();
        permissionbut = new javax.swing.JButton();
        leavebut = new javax.swing.JButton();
        logoutbut = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");
        setLocationRelativeTo(null);

        jLabel1.setText("ADMIN PAGE");
          logoutbut.setText("Logout");
        logoutbut.addActionListener(this::logoutbutActionPerformed);
 usersbut.setText("Users");
        tasksbut.setText("Tasks");
        projectsbut.setText("Projects");
        employeebut.setText("Employees");
        timecardsbut.setText("Time Cards");
        missionbut.setText("Missions");
        permissionbut.setText("Permissions");
        leavebut.setText("Leave");

        jLabel2.setText("HELLO ADMIN");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(usersbut)
                .addComponent(tasksbut)
                .addComponent(projectsbut)
                .addComponent(employeebut)
                .addComponent(timecardsbut)
                .addComponent(missionbut)
                .addComponent(permissionbut)
                .addComponent(leavebut)
                .addComponent(logoutbut)
        );

        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addGap(20)
                .addComponent(jLabel1)
                .addGap(10)
                .addComponent(jLabel2)
                .addGap(20)
                .addComponent(usersbut)
                .addComponent(tasksbut)
                .addComponent(projectsbut)
                .addComponent(employeebut)
                .addComponent(timecardsbut)
                .addComponent(missionbut)
                .addComponent(permissionbut)
                .addComponent(leavebut)
                .addGap(20)
                .addComponent(logoutbut)
        );

        pack();
    }
    

    /**
     * Creates new form adminf
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usersbut = new javax.swing.JButton();
        tasksbut = new javax.swing.JButton();
        projectsbut = new javax.swing.JButton();
        employeebut = new javax.swing.JButton();
        timecardsbut = new javax.swing.JButton();
        missionbut = new javax.swing.JButton();
        permissionbut = new javax.swing.JButton();
        leavebut = new javax.swing.JButton();
        logoutbut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("admin page");

        usersbut.setText("users ");

        tasksbut.setText("tasks");

        projectsbut.setText("projects");

        employeebut.setText("employee");

        timecardsbut.setText("time cards");

        missionbut.setText("missions");

        permissionbut.setText("permissions");

        leavebut.setText("leave ");

        logoutbut.setText("log out ");
        logoutbut.addActionListener(this::logoutbutActionPerformed);

        jLabel2.setText("HELLO \"today is a new chance to do better\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(permissionbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usersbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectsbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeebut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(missionbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timecardsbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leavebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usersbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tasksbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectsbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeebut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timecardsbut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(missionbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permissionbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leavebut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(logoutbut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbutActionPerformed
         System.out.println("Logout button clicked!");
                dispose(); // close current frame
                new Loginf().setVisible(true); // show login frame
    }//GEN-LAST:event_logoutbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Adminf().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton leavebut;
    private javax.swing.JButton logoutbut;
    private javax.swing.JButton missionbut;
    private javax.swing.JButton permissionbut;
    private javax.swing.JButton projectsbut;
    private javax.swing.JButton tasksbut;
    private javax.swing.JButton timecardsbut;
    private javax.swing.JButton usersbut;
    // End of variables declaration//GEN-END:variables

}