/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import core.Admin;
import main.Loginf;

public class Adminf extends javax.swing.JFrame {
    private Admin admin;
    public Adminf() {
        initComponents();
    } 
    public Adminf(Admin admin) {
        this.admin = admin;
        initComponents();
        welcomeAdmin();
    }
     private void welcomeAdmin() {
        if (admin != null) {
            jLabel2.setText("HELLO " + admin.getEmail() +
                    " - Today is a new chance to do better");
        }
    }
     @SuppressWarnings("unchecked")
    
//    private void addActions() {
//       tasksbut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Tasks page"));
//        projectsbut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Projects page"));
//        employeebut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Employees page"));
//
//       timecardsbut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Time Cards page"));
//
//        missionbut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Missions page"));
//        permissionbut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Permissions page"));
//
//        leavebut.addActionListener(e ->
//                JOptionPane.showMessageDialog(this, "Leave page"));
//
//        
//    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tasksbut = new javax.swing.JButton();
        projectsbut = new javax.swing.JButton();
        employeebut = new javax.swing.JButton();
        timecardsbut = new javax.swing.JButton();
        missionbut = new javax.swing.JButton();
        permissionbut = new javax.swing.JButton();
        leavebut = new javax.swing.JButton();
        logoutbut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMIN PAGE");

        tasksbut.setText("tasks");
        tasksbut.addActionListener(this::tasksbutActionPerformed);

        projectsbut.setText("projects");

        employeebut.setText("employee");

        timecardsbut.setText("time cards");

        missionbut.setText("missions");

        permissionbut.setText("permissions");

        leavebut.setText("leave ");

        logoutbut.setText("log out ");
        logoutbut.addActionListener(this::logoutbutActionPerformed);

        jLabel2.setText("HELLO \"today is a new chance to do better\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(permissionbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectsbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeebut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasksbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(missionbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timecardsbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(leavebut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutbut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tasksbut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectsbut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(employeebut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timecardsbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(missionbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(permissionbut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(leavebut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(logoutbut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbutActionPerformed
         System.out.println("Logout button clicked!");
                dispose(); // close current frame
                new Loginf().setVisible(true); // show login frame
    }//GEN-LAST:event_logoutbutActionPerformed

    private void tasksbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksbutActionPerformed
        this.dispose();
        new Tasksf(this.admin).setVisible(true);
    }//GEN-LAST:event_tasksbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.getLogger(Adminf.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Adminf().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton employeebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton leavebut;
    private javax.swing.JButton logoutbut;
    private javax.swing.JButton missionbut;
    private javax.swing.JButton permissionbut;
    private javax.swing.JButton projectsbut;
    private javax.swing.JButton tasksbut;
    private javax.swing.JButton timecardsbut;
    // End of variables declaration//GEN-END:variables

}