/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import utils.*;
import core.*;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author HP
 */
public class Tasksf extends javax.swing.JFrame {
    private boolean isAdmin;
    private Employee employee;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tasksf.class.getName());

    public Tasksf(Employee employee) {
        initComponents();
        this.isAdmin = false;
        setupTableEditors();
        setupTableEditors2();
        setupTableEditors3();
        setupTableEditors4();
        loadTasks();
        initTable();
    }
    public Tasksf(Admin admin) {
        initComponents();
        this.isAdmin = true;
        setupTableEditors();
        setupTableEditors2();
        setupTableEditors3();
        setupTableEditors4();
        loadTasks();
        initTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id ", "Title", "Discreption", "Priorty", "Phase", "Project", "Employee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tasksTable);

        jLabel1.setText("      Tasks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        // java.awt.EventQueue.invokeLater(() -> new Tasksf().setVisible(true));
    }
    private void setupTableEditors() {
        String[] statusOptions = { "PENDING", "APPROVED", "REJECTED" };
        JComboBox<String> statusCombo = new JComboBox<>(statusOptions);
        statusCombo.setEditable(false);

        TableColumn statusColumn =
            tasksTable.getColumnModel().getColumn(4);

        statusColumn.setCellEditor(
            new DefaultCellEditor(statusCombo)
        );
    }
    
    private void setupTableEditors2() {
        String[] statusOptions = { "LOW", "MEDIUM", "HIGH", "URGENT" };
        JComboBox<String> statusCombo = new JComboBox<>(statusOptions);
        statusCombo.setEditable(false);

        TableColumn statusColumn =
            tasksTable.getColumnModel().getColumn(3);

        statusColumn.setCellEditor(
            new DefaultCellEditor(statusCombo)
        );
    }
    
    private void setupTableEditors3() {
        Query q = new Query(FileManager.FILES.PROJECTS);
        ArrayList<Project> projects = Project.findAll(q);

        // 1. Create a JComboBox that holds Project objects
        JComboBox<Project> projectCombo = new JComboBox<>();

        // 2. Add Project objects directly to the model
        for (Project p : projects) {
            projectCombo.addItem(p);
        }

        // 3. Use a Renderer to show only the Name to the user
        projectCombo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, 
                    int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Project) {
                    Project p = (Project) value;
                    setText(p.getName()); // What the user sees
                }
                return this;
            }
        });

        // 4. Set as the cell editor
        TableColumn statusColumn = tasksTable.getColumnModel().getColumn(5);
        statusColumn.setCellEditor(new DefaultCellEditor(projectCombo));
    }
    
    private void setupTableEditors4() {
        // 1. Fetch the data
        Query q = new Query(FileManager.FILES.EMPLOYEES);
        ArrayList<Employee> employees = Employee.findAll(q);

        // 2. Initialize the ComboBox
        JComboBox<String> statusCombo = new JComboBox<>();
        statusCombo.setEditable(false);

        // 3. Populate the ComboBox with Project names
        for (Employee employee : employees) {
            statusCombo.addItem(employee.getName()); // Assuming the getter is getName()
        }

        // 4. Assign to the TableColumn
        TableColumn statusColumn = tasksTable.getColumnModel().getColumn(6);
        statusColumn.setCellEditor(new DefaultCellEditor(statusCombo));
    }
    
    private void initTable() {
        tasksTable.putClientProperty("terminateEditOnFocusLost", true);
        tasksTable.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    e.consume(); // stop JTable default behavior
                    saveCurrentRow();
                }
            }
        });
    } 
    
    private void loadTasks() {
        DefaultTableModel model = (DefaultTableModel) tasksTable.getModel();
        model.setRowCount(0); // clear table first

        Query q = new Query(FileManager.FILES.TASKS);
        ArrayList<Task> tasks = Task.findAll(q);

        for (Task task : tasks) {
            model.addRow(Query.splitRow(task.toRow(true)));
        }
        model.addRow(new String[]{ UID.generate(), "", "", "", "", "", "" });
    }
    
    private void saveCurrentRow() {
        int row = tasksTable.getSelectedRow();
        System.out.println(row);
        if (row == -1) return;

        DefaultTableModel model = (DefaultTableModel) tasksTable.getModel();

        String id = get(model, row, 0);
        String title = get(model, row, 1);

        System.out.println(id + " " + title + " " + get(model, row, 3));
    }
    
    private String get(DefaultTableModel m, int r, int c) {
        Object v = m.getValueAt(r, c);
        return v == null ? "" : v.toString().trim();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tasksTable;
    // End of variables declaration//GEN-END:variables
}
